# Generated by Django 3.0.2 on 2020-01-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parents',
            new_name='parent',
        ),
    ]
